version: "3.8"
services:
  dbm:
    hostname: dbm
    image: postgres:15
    env_file:
      - .env
    ports: 
      - "127.0.0.1:5433:5432"
    networks:
      - db_net
    volumes:
      - dbm-data:/var/lib/postgresql/data
    
  dbs:
    hostname: dbs
    image: postgres:15
    env_file:
      - .env
    ports: 
      - "127.0.0.1:5434:5432"
    networks:
      - db_net
    volumes:
      - dbs-data:/var/lib/postgresql/data
  
networks:
  db_net:
    driver: bridge
  
volumes:
  dbm-data:
  dbs-data: